### ISSUE TITLE
[ FIX ] Installation for mac and linux doesn't show up

### ISSUE THREAD

**Issue by Arnav-2004** [DudeBro249/docrunner#76]
For some reason the below doesn't show on the [getting-started](https://docrunner-cli.web.app/docs/getting-started) page.<br><br>

Shell (Mac, Linux):
```shell
curl -fsSL https://raw.githubusercontent.com/DudeBro249/docrunner/dev/installers/install.sh | sh
```

![image](https://user-images.githubusercontent.com/70969910/123537025-13d24b00-d74b-11eb-9d1d-dba317a84c3f.png)

**Comment by srinivasayush** [comment]
Thanks for the catch! Will work on a fix right away.

**Comment by srinivasayush** [comment]
#87 was merged, fixing this issue! Thanks once again @Arnav-2004 for bringing this up!
