### ISSUE TITLE
Linux & Mac support

### ISSUE THREAD

**Issue by jbutcher5** [DudeBro249/docrunner#77]
Currently docrunner only supports Windows, we should aim to support both mac and linux as well, this can be achieved by adding continuous deployment in the form of a Github workflow and release every time a branch is merged into the "stable" branch. In addition the shell install script must be fixed as this is installing a windows binary in a C drive on linux.

**Comment by srinivasayush** [comment]
These are some great point-outs! Would you be willing to make the necessary fixes?

**Comment by jbutcher5** [comment]
I would be able to make the required changes.

**Comment by srinivasayush** [comment]
Great work @KJ002! 🥳 🚀
